coverage:
  precision: 2      # Report coverage to 2 decimal places
  round: down       # Round down
  range: "90...100" # Anything below 90% is coloured red (considered bad)
  status:           # Various customisations that it seems should be off
    project: off
    patch: off
    changes: off

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
 - "extern"         # Do not check coverage on the extern directory
