coverage:
  precision: 2      # Report coverage to 2 decimal places
  round: down       # Round down
  range: "90...100" # Anything below 90% is coloured red (considered bad)

  status: # GitHub status checks to add to a PR
    project: # Check all of Digraphs
      default:
        informational: true # Don't fail the check if overall coverage decreases
    patch: # Check only the PR's diff
      default:
        target: 100
        threshold: 0
        informational: false # Do fail the check if the diff is not 100% covered
    changes: # Information about changes in coverage outside the diff
      default:
        informational: true # Don't fail the check

# Comment to post on PRs
comment: false

ignore:
 - "extern/"
 - "gap/utils.gi"
 - "PackageInfo.g"
 - "init.g"
 - "makedoc.g"
 - "read.g"
 - "tst/testall.g"
