name: Digraphs
version: 1.9.0
date: 2024-09-06
description: |
    Graphs, digraphs, and multidigraphs in GAP

authors:
    - name: Jan De Beule
      url: http://homepages.vub.ac.be/~jdbeule/
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: James Mitchell
      url: https://jdbm.me
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk
    - name: Marina Anagnostopoulou-Merkouri
      url: mailto:mam49@st-andrews.ac.uk
    - name: Finn Buck
      url: mailto:finneganlbuck@gmail.com
    - name: Stuart Burrell
      url: https://stuartburrell.github.io
    - name: Graham Campbell
    - name: Raiyan Chowdhury
    - name: Reinis Cirpons
      url: mailto:rc234@st-andrews.ac.uk
    - name: Ashley Clayton
      url: mailto:ac323@st-andrews.ac.uk
    - name: Tom Conti-Leslie
      url: https://tomcontileslie.com
    - name: Joseph Edwards
      url: https://github.com/Joseph-Edwards
    - name: Luna Elliott
      url: mailto:TODO
    - name: Isuru Fernando
      url: mailto:isuruf@gmail.com
    - name: Ewan Gilligan
      url: mailto:eg207@st-andrews.ac.uk
    - name: Sebastian Gutsche
      url: mailto:gutsche@momo.math.rwth-aachen.de
    - name: Samantha Harper
      url: mailto:seh25@st-andrews.ac.uk
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Hyeokjun Kwon
      url: mailto:hk78@st-andrews.ac.uk
    - name: Andrea Lee
      url: mailto:ahwl1@st-andrews.ac.uk
    - name: Saffron McIver
      url: mailto:sm544@st-andrews.ac.uk
    - name: Michael Orlitzky
      url: https://michael.orlitzky.com/
    - name: Matthew Pancer
      url: mailto:mp322@st-andrews.ac.uk
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Daniel Pointon
      url: mailto:dp211@st-andrews.ac.uk
    - name: Lea Racine
      url: mailto:lr217@st-andrews.ac.uk
    - name: Christopher Russell
    - name: Artur Schaefer
      url: mailto:as305@st-and.ac.uk
    - name: Isabella Scott
      url: mailto:iscott@uchicago.edu
    - name: Kamran Sharma
      url: mailto:kks4@st-andrews.ac.uk
    - name: Finn Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: Ben Spiers
      url: mailto:bspiers972@outlook.com
    - name: Maria Tsalakou
      url: https://mariatsalakou.github.io/
    - name: Meike Weiss
      url: https://bit.ly/4e6pUeP
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk
    - name: Fabian Zickgraf
      url: mailto:f.zickgraf@dashdos.com

maintainers:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk

GAP: ">=4.10.0"

needed-pkgs:
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"
    - name: "datastructures"
      version: ">=0.2.5"
      url: "https://gap-packages.github.io/datastructures"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">=1.6.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.8.1"
      url: "https://gap-packages.github.io/grape"
    - name: "nautytracesinterface"
      version: ">=0.2"
      url: "https://gap-packages.github.io/NautyTracesInterface/"
    - name: "AutoDoc"
      version: ">=2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://digraphs.github.io/Digraphs
readme: README.md
packageinfo: https://digraphs.github.io/Digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/digraphs/Digraphs/releases/download/v1.9.0/digraphs-1.9.0.tar.gz

abstract: |
    The &Digraphs; package is a &GAP; package containing
              methods for graphs, digraphs, and multidigraphs.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
