name: Digraphs
version: 1.5.2
date: 2022-03-30
description: |
    Graphs, digraphs, and multidigraphs in GAP

authors:
    - name: Jan De Beule
      url: http://homepages.vub.ac.be/~jdbeule/
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: James Mitchell
      url: https://jdbm.me
    - name: Maria Tsalakou
      url: https://mariatsalakou.github.io/
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk

maintainers:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Wilf A. Wilson
      url: https://wilf.me

contributors:
    - name: Marina Anagnostopoulou-Merkouri
      url: mailto:mam49@st-andrews.ac.uk
    - name: Finn Buck
      url: mailto:flb5@st-andrews.ac.uk
    - name: Stuart Burrell
      url: mailto:sb235@st-andrews.ac.uk
    - name: Reinis Cirpons
      url: mailto:rc234@st-andrews.ac.uk
    - name: Tom Conti-Leslie
      url: mailto:tdcl@st-andrews.ac.uk
    - name: Luke Elliott
      url: mailto:le27@st-andrews.ac.uk
    - name: Ewan Gilligan
      url: mailto:eg207@st-andrews.ac.uk
    - name: Samantha Harper
      url: mailto:seh25@st-andrews.ac.uk
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk
    - name: Markus Pfeiffer
      url: https://www.morphism.de/~markusp
    - name: Lea Racine
      url: mailto:lr217@st-andrews.ac.uk
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk
    - name: Finn Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: Ben Spiers
      url: mailto:bs201@st-andrews.ac.uk
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk

GAP: ">=4.10.0"

needed-pkgs:
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"
    - name: "datastructures"
      version: ">=0.2.5"
      url: "https://gap-packages.github.io/datastructures"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">=1.6.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.8.1"
      url: "https://gap-packages.github.io/grape"
    - name: "nautytracesinterface"
      version: ">=0.2"
      url: "https://gap-packages.github.io/NautyTracesInterface/"

www: https://digraphs.github.io/Digraphs
readme: README.md
packageinfo: https://digraphs.github.io/Digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/digraphs/Digraphs/releases/download/v1.5.2/digraphs-1.5.2.tar.gz

abstract: |
    The <b>Digraphs</b> package is a <b>GAP</b> package for digraphs and multidigraphs.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
