name: Digraphs
version: 0.7.0
date: 14/03/2017
description: 

authors:
    - name: J. De Beule
      url: http://homepages.vub.ac.be/~jdbeule/
    - name: L. Elliott
      url: mailto:le27@st-andrews.ac.uk
    - name: J. Jonusas
      url: http://www-circa.mcs.st-andrews.ac.uk/~julius/
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6
    - name: M. Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: F. Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: M. Torpey
      url: http://www-circa.mcs.st-andrews.ac.uk/~mct25/
    - name: W. A. Wilson
      url: http://www-circa.mcs.st-andrews.ac.uk/~waw7/

maintainers:
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6

GAP: ">=4.8.2"

needed-pkgs:
    - name: "io"
      version: ">=4.4.4"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.7.5"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.5"
      url: "http://www.maths.qmul.ac.uk/~leonard/grape/"

www: https://gap-packages.github.io/Digraphs
readme: https://gap-packages.github.io/Digraphs/README.md
packageinfo: https://gap-packages.github.io/Digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Digraphs/releases/download/v0.7.0/digraphs-0.7.0.tar.gz

abstract: The <b>Digraphs</b> package is a <b>GAP</b> package for digraphs and multidigraphs.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
