name: Digraphs
version: "1.11.0"
license: "GPL-3.0-or-later"
date: 2025-08-28
description: |
    Graphs, digraphs, and multidigraphs in GAP

authors:
    - name: Jan De Beule
      url: https://wids.research.vub.be/en/jan-de-beule
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: James Mitchell
      url: https://jdbm.me
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://myoung.uk/work/
    - name: Marina Anagnostopoulou-Merkouri
      url: mailto:mam49@st-andrews.ac.uk
    - name: Finn Buck
      url: mailto:finneganlbuck@gmail.com
    - name: Stuart Burrell
      url: https://stuartburrell.github.io
    - name: Graham Campbell
    - name: Raiyan Chowdhury
    - name: Reinis Cirpons
      url: mailto:rc234@st-andrews.ac.uk
    - name: Ashley Clayton
      url: mailto:ac323@st-andrews.ac.uk
    - name: Tom Conti-Leslie
      url: https://tomcontileslie.com
    - name: Joseph Edwards
      url: https://github.com/Joseph-Edwards
    - name: Luna Elliott
      url: https://research.manchester.ac.uk/en/persons/luna-elliott
    - name: Isuru Fernando
      url: mailto:isuruf@gmail.com
    - name: Ewan Gilligan
      url: mailto:eg207@st-andrews.ac.uk
    - name: Gillis Frankie
      url: mailto:fotg1@st-andrews.ac.uk
    - name: Sebastian Gutsche
      url: mailto:gutsche@momo.math.rwth-aachen.de
    - name: Samantha Harper
      url: mailto:seh25@st-andrews.ac.uk
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Harry Jack
      url: mailto:hrj4@st-andrews.ac.uk
    - name: Christopher Jefferson
      url: https://heather.cafe/
    - name: Malachi Johns
      url: mailto:zlj1@st-andrews.ac.uk
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Hyeokjun Kwon
      url: mailto:hk78@st-andrews.ac.uk
    - name: Aidan Lau
    - name: Andrea Lee
      url: mailto:ahwl1@st-andrews.ac.uk
    - name: Saffron McIver
      url: mailto:sm544@st-andrews.ac.uk
    - name: Seyyed Ali Mohammadiyeh
      url: mailto:MaxBaseCode@Gmail.Com
    - name: Michael Orlitzky
      url: https://michael.orlitzky.com/
    - name: Matthew Pancer
      url: mailto:mp322@st-andrews.ac.uk
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Daniel Pointon
      url: mailto:dp211@st-andrews.ac.uk
    - name: Pramoth Ragavan
      url: mailto:107881923+pramothragavan@users.noreply.github.com
    - name: Lea Racine
      url: mailto:lr217@st-andrews.ac.uk
    - name: Christopher Russell
    - name: Artur Schaefer
      url: mailto:as305@st-and.ac.uk
    - name: Isabella Scott
      url: mailto:iscott@uchicago.edu
    - name: Kamran Sharma
      url: mailto:kks4@st-andrews.ac.uk
    - name: Finn Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: Ben Spiers
      url: mailto:bspiers972@outlook.com
    - name: Maria Tsalakou
      url: https://mariatsalakou.github.io/
    - name: Agastyaa Vishvanath
      url: mailto:av215@st-andrews.ac.uk
    - name: Meike Weiss
      url: https://bit.ly/4e6pUeP
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk
    - name: Fabian Zickgraf
      url: mailto:f.zickgraf@dashdos.com

maintainers:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://myoung.uk/work/

GAP: ">=4.10.0"

needed-pkgs:
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"
    - name: "datastructures"
      version: ">=0.2.5"
      url: "https://gap-packages.github.io/datastructures"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">=1.6.3"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.8.1"
      url: "https://gap-packages.github.io/grape"
    - name: "nautytracesinterface"
      version: ">=0.2"
      url: "https://gap-packages.github.io/NautyTracesInterface/"
    - name: "AutoDoc"
      version: ">=2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://digraphs.github.io/Digraphs
readme: README.md
changes: CHANGELOG.md
packageinfo: https://digraphs.github.io/Digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/digraphs/Digraphs/releases/download/v1.11.0/digraphs-1.11.0.tar.gz

abstract: |
    The &Digraphs; package is a &GAP; package containing
              methods for graphs, digraphs, and multidigraphs.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BJMWYABBCCCCCEEFGFGHHJJJKKLLMMOPPPRRRSSSSSTVWWZ25</span>]   <b class='BibAuthor'>De Beule, J., Jonusas, J., Mitchell, J., Wilson, W. A., Young, M., Anagnostopoulou-Merkouri, M., Buck, F., Burrell, S., Campbell, G., Chowdhury, R., Cirpons, R., Clayton, A., Conti-Leslie, T., Edwards, J., Elliott, L., Fernando, I., Gilligan, E., Frankie, G., Gutsche, S., Harper, S., Horn, M., Jack, H., Jefferson, C., Johns, M., Konovalov, O., Kwon, H., Lau, A., Lee, A., McIver, S., Mohammadiyeh, S. A., Orlitzky, M., Pancer, M., Pfeiffer, M., Pointon, D., Ragavan, P., Racine, L., Russell, C., Schaefer, A., Scott, I., Sharma, K., Smith, F., Spiers, B., Tsalakou, M., Vishvanath, A., Weiss, M., Whyte, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>Digraphs, Graphs, digraphs, and multidigraphs in GAP,
             Version 1.11.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://digraphs.github.io/Digraphs">https://digraphs.github.io/Digraphs</a></span>.
    </p>
    

bibtex: |
    @misc{ Digraphs,
      author =           {De  Beule,  J.  and  Jonusas,  J. and Mitchell, J. and
                          Wilson,     W.     A.     and     Young,     M.    and
                          Anagnostopoulou\texttt{\symbol{45}}Merkouri,   M.  and
                          Buck,   F.  and  Burrell,  S.  and  Campbell,  G.  and
                          Chowdhury,  R.  and  Cirpons,  R.  and Clayton, A. and
                          Conti\texttt{\symbol{45}}Leslie,  T.  and  Edwards, J.
                          and  Elliott, L. and Fernando, I. and Gilligan, E. and
                          Frankie,  G.  and Gutsche, S. and Harper, S. and Horn,
                          M.  and  Jack,  H. and Jefferson, C. and Johns, M. and
                          Konovalov, O. and Kwon, H. and Lau, A. and Lee, A. and
                          McIver,  S.  and  Mohammadiyeh, S. A. and Orlitzky, M.
                          and  Pancer,  M.  and Pfeiffer, M. and Pointon, D. and
                          Ragavan,  P.  and  Racine,  L.  and  Russell,  C.  and
                          Schaefer,  A.  and Scott, I. and Sharma, K. and Smith,
                          F.  and Spiers, B. and Tsalakou, M. and Vishvanath, A.
                          and Weiss, M. and Whyte, M. and Zickgraf, F.},
      title =            {{Digraphs},  {Graphs,  digraphs,  and multidigraphs in
                          GAP}, {V}ersion 1.11.0},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href            {https://digraphs.github.io/Digraphs}
                          {\texttt{https://digraphs.github.io/}\discretionary
                          {}{}{}\texttt{Digraphs}}},
      keywords =         {},
      printedkey =       {BJMWYABBCCCCCEEFGFGHHJJJKKLLMMOPPPRRRSSSSSTVWWZ25}
    }

