name: GitHubPagesForGAP
version: "0.2"
license: "0BSD"
date: 2017-02-04
description: |
    A GitHub Pages generator for GAP packages

authors:
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: A. U. Thor

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Jan Itor

GAP: ">=4.8.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.1"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "orb"
      version: ">= 4.2"
      url: "https://gap-packages.github.io/orb"

www: https://gap-system.github.io/GitHubPagesForGAP/
readme: README.md
packageinfo: https://gap-system.github.io/GitHubPagesForGAP/PackageInfo.g
github: https://github.com/gap-system/GitHubPagesForGAP

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-system/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.bz2

abstract: |
    This is a pseudo package that contains no actual  <span class="pkgname">GAP</span> code. Instead, it is a template for other  GAP packages that allows to quickly setup GitHub Pages.

status: other
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    GitHub Pages, GAP.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HTI17</span>]   <b class='BibAuthor'>Horn, M., Thor, A. U. and Itor, J.</b>,
     <i class='BibTitle'>GitHubPagesForGAP, A GitHub Pages generator for GAP packages,
             Version 0.2</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-system.github.io/GitHubPagesForGAP/">https://gap-system.github.io/GitHubPagesForGAP/</a></span>.
    </p>
    

bibtex: |
    @misc{ GitHubPagesForGAP0.2,
      author =           {Horn, M. and Thor, A. U. and Itor, J.},
      title =            {{GitHubPagesForGAP}, A GitHub Pages generator for GAP packages, {V}ersion 0.2},
      month =            {Feb},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href                              {https://gap-system.github.io/GitHubPagesForGAP/}
                          {\texttt{https://gap-system.github.io/}\discretionary
                          {}{}{}\texttt{GitHubPagesForGAP/}}},
      keywords =         {GitHub Pages; GAP},
      printedkey =       {HTI17}
    }

