name: "CI"

# Trigger the workflow on push or pull request
on:
  pull_request:
  push:
    branches-ignore:
      - rc-v[0-9]+.[0-9]+.[0-9]+

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies . . ."
        run: |
          sudo pip install gaplint cpplint
      - name: "Run gaplint + cpplint . . ."
        run: bash etc/lint.sh
  test:
    name: "GAP ${{ matrix.gap-branch }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        digraphs-lib:
          - digraphs-lib-0.6
        gap-branch:
          - master
          - stable-4.11

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
        with:
          GAP_PKGS_TO_CLONE: "NautyTracesInterface"
          GAP_PKGS_TO_BUILD: "io orb profiling grape NautyTracesInterface datastructures"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: "Install digraphs-lib"
        run: curl --retry 5 -L -O https://digraphs.github.io/Digraphs/${{ matrix.digraphs-lib }}.tar.gz
             && tar xf ${{ matrix.digraphs-lib }}.tar.gz
      - uses: gap-actions/run-test-for-packages@v1
