name: OS
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - stable-*.*
  schedule:
    # Every day at 3:30 AM UTC
    - cron: 30 3 * * *

env:
  DIGRAPHS_LIB: digraphs-lib-0.7

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}${{ matrix.ABI }} / GAP stable-4.15
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            ABI: 32
            pkgs-to-clone: https://github.com/digraphs/graphviz.git
            pkgs-to-build: io orb datastructures grape
          - os: macos
            ABI: 64
            pkgs-to-clone: https://github.com/digraphs/graphviz.git https://github.com/gap-packages/NautyTracesInterface.git
            pkgs-to-build: io orb datastructures grape NautyTracesInterface
          - os: windows
            ABI: 64
            pkgs-to-clone: https://github.com/digraphs/graphviz.git https://github.com/gap-packages/NautyTracesInterface.git
            pkgs-to-build: io orb datastructures grape NautyTracesInterface


    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-cygwin@v2
        if: ${{ runner.os == 'Windows' }}
      - name: Output g++ version . . .
        run: g++ --version
      - name: Install macOS dependencies . . .
        if: ${{ runner.os == 'macOS' }}
        run: brew install automake
      - name: "Install 32-bit packages . . ."
        if: ${{ matrix.ABI == '32' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          packages=(
            libgmp-dev:i386
            libreadline-dev:i386
            zlib1g-dev:i386
            gcc-multilib
            g++-multilib
          )
          sudo apt-get install "${packages[@]}"
      - name: "Install GAP . . ."
        uses: gap-actions/setup-gap@v3
        env:
          ABI: ${{ matrix.ABI }}
        with:
          gap-version: stable-4.15
          ABI: ${{ matrix.ABI }}
      - name: "Install necessary GAP package clones . . ."
        shell: bash
        run: |
          for PKG in ${{ matrix.pkgs-to-clone }}; do
            cd ${GAPROOT}/pkg
            git clone $PKG
          done
      - name: "Build additional necessary GAP packages . . ."
        shell: bash
        env:
          ABI: ${{ matrix.ABI }}
        run: |
          cd ${GAPROOT}/pkg
          ../bin/BuildPackages.sh --strict ${{ matrix.pkgs-to-build }}
      - name: Build Digraphs . . .
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ matrix.ABI }}
      - name: Install digraphs-lib . . .
        run: |
          curl --retry 5 -L -O "https://digraphs.github.io/Digraphs/${{ env.DIGRAPHS_LIB }}.tar.gz"
          tar xf "${{ env.DIGRAPHS_LIB }}.tar.gz"
      - name: Run DigraphsTestInstall . . .
        uses: gap-actions/run-pkg-tests@v4
        with:
          coverage: false
          testfile: tst/github_actions/install.g
      - name: Run DigraphsTestStandard . . .
        uses: gap-actions/run-pkg-tests@v4
        with:
          coverage: false
          testfile: tst/github_actions/standard.g
      - name: Run DigraphsTestManualExamples . . .
        uses: gap-actions/run-pkg-tests@v4
        with:
          coverage: false
          testfile: tst/github_actions/examples.g
      - name: Run DigraphsTestExtreme . . .
        uses: gap-actions/run-pkg-tests@v4
        if: ${{ runner.os != 'Windows' }}
        with:
          coverage: false
          testfile: tst/github_actions/extreme.g
